"use client";

// import type { Metadata } from "next";
import "./globals.css";
import { ProductProvider } from "@/components/context/productContext";
import { Provider } from "react-redux";
import { store } from "./store";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "skyblue" }}>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
